In [2]:
import torch
import numpy as np

In [1]:
#测试GPu

flag = torch.cuda.is_available()
print(flag)

ngpu= 1
# Decide which device we want to run on
device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
print(device)
print(torch.cuda.get_device_name(0))
print(torch.rand(3,3).cuda()) 

True
cuda:0
GeForce RTX 2060
tensor([[0.3017, 0.0875, 0.7190],
        [0.5586, 0.6092, 0.3546],
        [0.1964, 0.8161, 0.2378]], device='cuda:0')


In [ ]:
# 模型加载

# 1.torch.save：将序列化的对象保存到disk。这个函数使用Python的pickle实用程序进行序列化。使用这个函数可以保存各种对象的模型、张量和字典。
# 2.torch.load：使用pickle unpickle工具将pickle的对象文件反序列化为内存。
# 3.torch.nn.Module.load_state_dict:使用反序列化状态字典加载model’s参数字典。

model.load_state_dict(torch.load(model_path))

In [2]:
# 模型部分基本格式

# class torch.nn.Module 是所有网络的基类。所有模型也应该继承这个类。
# Modules也可以包含其它Modules,允许使用树结构嵌入他们。你可以将子模块赋值给模型属性。

import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)     
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
       x = F.relu(self.conv1(x))
       y = F.relu(self.conv2(x))
       return y

In [3]:
# 将tensor指定index排序

torch.tensor([2,3,1])[torch.tensor([2,0,1])]

tensor([1, 2, 3])

In [6]:
# CPU张量和GPU张量是否可以计算

device = torch.device('cuda:0')
a = torch.tensor([1,2,3])
print(a)
b = torch.tensor([1,2,3]).to(device)
print(b)

# 会报错
# print(a+b)

tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')


In [19]:
train_x = np.random.rand(25,3)

trainx = torch.from_numpy(np.reshape(train_x, newshape=(-1,25)))


In [12]:
np.array([1,2])

array([1, 2])

In [7]:
np.array([1,2]).append(np.array([3,4]))

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
np.float32

numpy.float32